// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.24.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SendFile {
  final String path;
  final String addr;

  const SendFile({
    required this.path,
    required this.addr,
  });

  @override
  int get hashCode => path.hashCode ^ addr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          addr == other.addr;
}
